### ISSUE TITLE
Top actie dit

### ISSUE THREAD

**Issue by Frank18000** [BrandonWill/GrepolisBot#1]
Hoi ben blij dat jullie hier mee bezig zijn ik heb geen verstand van programmeren maar wil graag testen voor jullie. Ik kan in loggen maar dan bevriest de bot en doet ie niks meer.
 

22:56:52 Selecting world
22:57:00 Bot enabled
22:57:00 csrftoken: e3cb66694a3
22:57:00 Default town: xxxxx
22:57:00 Towns found: 4
Exception in thread "Thread-130" java.lang.NullPointerException
        at Grepolis.GrepolisBot$BuildTheBuildings.run(GrepolisBot.java:501)
        at java.lang.Thread.run(Unknown Source)

**Comment by Frank18000** [comment]
Wat aanvullende info

Exception in thread "Thread-130" java.lang.NullPointerException
        at Grepolis.GrepolisBot$BuildTheBuildings.run(GrepolisBot.java:501)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at Grepolis.IO.Saver.saveBuildings(Saver.java:78)
        at Grepolis.IO.Saver.save(Saver.java:22)
        at Grepolis.GrepolisBot$2.windowClosing(GrepolisBot.java:101)
        at java.awt.Window.processWindowEvent(Unknown Source)
        at javax.swing.JFrame.processWindowEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at Grepolis.IO.Saver.saveBuildings(Saver.java:78)
        at Grepolis.IO.Saver.save(Saver.java:22)
        at Grepolis.GrepolisBot$2.windowClosing(GrepolisBot.java:101)
        at java.awt.Window.processWindowEvent(Unknown Source)
        at javax.swing.JFrame.processWindowEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by BrandonWill** [comment]
You closed the issue, did it fix itself?

**Comment by Frank18000** [comment]
I had locked the issue accidentally . The bot I downloaded yesterday via the zip so assume that it is the latest

**Comment by BrandonWill** [comment]
Hmm, found the issue. It wasn't able to find the senate and several other buildings. Working on an update now

**Comment by BrandonWill** [comment]
Issue should be fixed!

**Comment by Frank18000** [comment]
great i go test it

**Comment by BrandonWill** [comment]
Reopening issue...

This fix solves the issue for the US server; however, the en server uses the other wording for descriptions. So the buildings now won't load for them. 

What server are you playing on?

**Comment by Frank18000** [comment]
i play on the dutch servers.

I ran the bot from the new zip file and it freezes

jar GrepolisBot_0.15.jar
java.io.FileNotFoundException: C:\Users\frank en ingrid\Desktop\GrepolisBot-master\Saves\AccountSave.txt (Het systeem kan het opgegeven pad niet vinden)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at Grepolis.IO.Loader.loadAccount(Loader.java:44)
        at Grepolis.IO.Loader.load(Loader.java:22)
        at Grepolis.GrepolisBot.initComponents(GrepolisBot.java:96)
        at Grepolis.GrepolisBot.<init>(GrepolisBot.java:75)
        at Grepolis.GrepolisBot$1.run(GrepolisBot.java:86)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
initializing variables
Account save file not found!
11:14:24 Browser agent changed to latest chrome version. It's now: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
11:15:18 Selecting world
11:15:36 Bot enabled
11:15:36 csrftoken: f35dec906ec
11:15:36 Default town: 62234
11:15:37 Towns found: 115
11:15:40 Not all buildings found. Please create an issue on Github! Pausing...
11:15:40 64 A6 Vision Nothing to build or building queue is full!

**Comment by BrandonWill** [comment]
Pushed another update. It should work for you now. It works on both us and en servers for me and no longer uses the description to find buildings.

**Comment by BrandonWill** [comment]
Tested on dutch server. Closing issue

**Comment by Frank18000** [comment]
It is reading the cities now great

is the bot looking to the city names or the bb code?

**Comment by BrandonWill** [comment]
It reads the city names from the captain. Is it not reading them correctly?

**Comment by Frank18000** [comment]
perfect 
but when you change a name does the bot understand this and uses te building que?

**Comment by BrandonWill** [comment]
Yeah it does! 

If you rename it, the next time you reload your cities, the bot will recognize it and keep your queue

**Comment by Frank18000** [comment]
it doesn't build troops the nummers i put in the que are not saved when i push the save button

**Comment by BrandonWill** [comment]
Has the bot read the city yet? It also won't save the numbers if the city doesn't have a barracks/docks

**Comment by Frank18000** [comment]
yes it did read the city 
i wil try farming next

**Comment by Frank18000** [comment]
farming works

**Comment by BrandonWill** [comment]
Alright.

I got my stuff to save for me on the de server. However, troop counts aren't being loaded

**Comment by Frank18000** [comment]
ok when farming is ready i close the bot en restart it and look at the troop counts

**Comment by Frank18000** [comment]
the bot doesn't make a save file

is that the problem?

**Comment by BrandonWill** [comment]
It should be creating one. It has to be closed from the jar file though

**Comment by Frank18000** [comment]
know it does it reads troeps every other city

**Comment by BrandonWill** [comment]
Should be fixed in the most recent version

**Comment by Frank18000** [comment]
okay i wil get the new version

**Comment by Frank18000** [comment]
the new version freezes

jar GrepolisBot_0.15.jar
12:59:14 Browser agent changed to latest chrome version. It's now: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
12:59:33 Selecting world
12:59:45 Bot enabled
12:59:45 csrftoken: 387fc79ae63
12:59:45 Default town: 62234
12:59:46 Towns found: 115
Exception in thread "Thread-142" java.lang.NullPointerException
        at Grepolis.GrepolisBot$BuildTheBuildings.run(GrepolisBot.java:512)
        at java.lang.Thread.run(Unknown Source)

**Comment by Frank18000** [comment]
17:30:30 Towns found: 115
Exception in thread "Thread-151" java.lang.NullPointerException
        at Grepolis.GrepolisBot$BuildTheBuildings.run(GrepolisBot.java:512)
        at java.lang.Thread.run(Unknown Source)

**Comment by BrandonWill** [comment]
Sorry, I went to sleep.

Fixed it

**Comment by Frank18000** [comment]
great i wil download and test it

**Comment by Frank18000** [comment]
it runs first load 116 cities

**Comment by Frank18000** [comment]
it's working great!!

**Comment by BrandonWill** [comment]
Good to hear!

**Comment by Frank18000** [comment]
2 things it doesn't read all the cities and i can not save bir in the que

**Comment by Frank18000** [comment]
this is how the dock save line looks. Tirime  is writen wrong is that the problem?
townID:72336,big_transporter:0,bireme:0,attack_ship:0,demolition_ship:0,small_transporter:0,trireme:0,colonize_ship:0,sea_monster:0,

**Comment by BrandonWill** [comment]
I took the spelling from the wiki: https://wiki.en.grepolis.com/wiki/Trireme

I'm able to save it on my account on en (started the bot from scratch). Is it loading your ships from the towns?

**Comment by Frank18000** [comment]
okay than is that not the problem
i loaded the last update en starteded the bot from scratch

**Comment by BrandonWill** [comment]
The most recent version will tell you if the docks/barracks aren't loaded when you attempt to save

**Comment by Frank18000** [comment]
okay great i will download it

**Comment by Frank18000** [comment]
hoi villages on an isle without farms arn't read in the bot

**Comment by BrandonWill** [comment]
Created a new issue for that
