### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by allessi10** [BrandonWill/GrepolisBot#15]
The bot doesn't work. It just says the farming  village "name" isn't ready to be farmed or is farmed to its' cap! The thing is that all the villages are ready to be farmed. I have updated java.

**Comment by allessi10** [comment]
also getting this. Exception in thread "JavaFX Application Thread" java.util.concurrent.RejectedExecutionException: Task com.sun.javafx.tk.RenderJob@16e7427 rejected from com.sun.javafx.tk.quantum.QuantumRenderer@11d1013[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 36093]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
        at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumRenderer.submitRenderJob(QuantumRenderer.java:218)
        at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:452)
        at com.sun.javafx.webkit.prism.PrismInvoker.invokeOnRenderThread(PrismInvoker.java:78)
        at com.sun.javafx.webkit.prism.WCRenderQueueImpl.disposeGraphics(WCRenderQueueImpl.java:53)
        at com.sun.webkit.graphics.WCRenderQueue.fwkDisposeGraphics(WCRenderQueue.java:149)
        at com.sun.webkit.WebPage.twkPostPaint(Native Method)
        at com.sun.webkit.WebPage.updateDirty(WebPage.java:285)
        at com.sun.webkit.WebPage.updateContent(WebPage.java:597)
        at com.sun.javafx.sg.prism.web.NGWebView.update(NGWebView.java:74)
        at javafx.scene.web.WebView.handleStagePulse(WebView.java:978)
        at javafx.scene.web.WebView.lambda$new$29(WebView.java:278)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:378)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task com.sun.javafx.tk.quantum.PaintRenderJob@1e9017e rejected from com.sun.javafx.tk.quantum.QuantumRenderer@11d1013[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 36093]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
        at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumRenderer.submitRenderJob(QuantumRenderer.java:218)
        at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:452)
        at com.sun.javafx.tk.quantum.EmbeddedScene.repaint(EmbeddedScene.java:157)
        at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:435)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:511)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)

**Comment by BrandonWill** [comment]
Captainless farming only works on servers on new servers with the batllepoint villages. Even then, it is still very buggy and can get you banned. If you want perfect farming, you must purchase captain.
