### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by Frank18000** [BrandonWill/GrepolisBot#21]
The bot doesn´t log in annymore

Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: ReferenceError: Can't find variable: angular
        at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
        at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at com.sun.webkit.WebPage.executeScript(WebPage.java:1455)
        at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
        at Grepolis.GrepolisBot$6$1$1.run(GrepolisBot.java:289)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)

**Comment by BrandonWill** [comment]
I already pushed out an update for this. You have to manually login now on the bot until I have free time to fix it

**Comment by Frank18000** [comment]
i have tried te login manuallybut it does not work (real life is more important)

**Comment by BrandonWill** [comment]
Login is now fixed. Nothing like learning a new obscure javascript library to automate this thing
